ga_analytics = ""
google_tag_manager_id = ""

giscus = false

[goatcounter_analytics]
enable = false              # enable it when official online
siteID = "yanbin"

[plausible_analytics]
enable = false                # to enable plausible analytics set to true.
websiteDomain = "example.com" # domain name of your website, most cases same as your base url

[matomo_analytics]
enable = false                      # To enable matomo analytics change to `true`.
websiteDomain = "yanbin.blog"       # Set the domain name of your website, in most cases same as your base URL this is required.
matomoDomain = "stats.yanbin.blog" # Set to Matomo domain
matomoSiteID = "1"                  # Default is set to 1, change this to the siteid being tracked